### PR TITLE
ASpeed/ASpeedGopBinPkg: Update X64/AArch64 Gop UEFI Driver

### PR DESCRIPTION
**Pull request by nhivp**
NOTE: The patch is derived from https://github.com/TommyHuang0527/Gop_test_repo

1.Update the X64/AArch64 UEFI GOP driver into v1.13.05. 2.Update the .inf version.
3.Add EDID detail timing divisor value check.

Reviewed-by: Nhi Pham <nhi@os.amperecomputing.com>
Tested-by: Nhi Pham <nhi@os.amperecomputing.com>

### CODE REVIEW

**Comment by nhivp** [comment]
@leiflindholm

**Comment by leiflindholm** [comment]
No objections from me. @nate-desimone ?

**Comment by nhivp** [comment]
Should we have active reviewer for the Drivers folder? I believe this patch from ASpeed has been submitting for about 1 month.

**Comment by leiflindholm** [comment]
> Should we have active reviewer for the Drivers folder? I believe this patch from ASpeed has been submitting for about 1 month.

edk2-non-osi is a bit weird, really. The reviewer role becomes completely different from what it means for open source. It would probably make the most sense if Aspeed could maintain their driver themselves.
But if anyone was to volunteer to look after Drivers as a whole, I'd be OK with that too.

**Comment by TommyHuang0527** [comment]
@leiflindholm and @nhivp 
Thanks for your help. Actually, we are glad to maintain these drivers by ourselves.  Do we need to update the mariner list and push it?

**Comment by leiflindholm** [comment]
> @leiflindholm and @nhivp Thanks for your help. Actually, we are glad to maintain these drivers by ourselves. Do we need to update the mariner list and push it?

@mdkinney thoughts? (I'm all for it, unsure about most suitable mechanics.)

**Comment by mdkinney** [comment]
I have no objections.

I agree this repo is different.  I think the Maintainers are mainly responsible for process, commit message format, and review of license (making sure each binary has one) and directory layout and where new components are added.

Review of the binary files by maintainers is not possible.  The contributor of a binary is responsible for testing and supporting if there are questions/issues.

**Comment by TommyHuang0527** [comment]
Below is our plan. We want to notice our UEFI binaries update after passed our internal test here. Then we will wait a couple of days or weeks for a response that comes from whom it may concern. After this all, we will push and merge these binaries here.

**Comment by TommyHuang0527** [comment]
@mdkinney and @leiflindholm 
Would you accept my suggestion?

**Pull request merged**
